---
title: "Gene Set Enrichment of Significant Genes extracted from RNA-seq data in Alzheimer's Disease Patients"
author: "Divya Shridar"
date: "28 Nov 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(dplyr)
library(DESeq2)
library(edgeR)
library(limma)
library(pheatmap)
library(ggplot2)
library(ggrepel)
library(RColorBrewer)
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(enrichplot)
```


```{r}
library(readr)
# import data
significant_genes <- read_tsv('data/significant_genes.tsv') 

# create input vector for gene enrichment
significant_genes_for_gse <- as.vector(significant_genes$logFC)  # p value vector
names(significant_genes_for_gse) <- as.vector(significant_genes$GeneID) # gene ids
significant_genes_for_gse <- significant_genes_for_gse[order(-significant_genes_for_gse)] # order ranked
significant_genes_for_gse
```
```{r}
ego_all <- gseGO(geneList   = significant_genes_for_gse,
              OrgDb        = org.Hs.eg.db,
              ont          = "ALL", ## Molecular Function (MF), Biological Process (BP), and Cellular Component (CC)
              nPerm        = 1000,
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = TRUE,
              by = "fgsea",
              pAdjustMethod = "none") 
```


```{r}
ego1 <- gseGO(geneList     = significant_genes_for_gse,
              OrgDb        = org.Hs.eg.db,
              ont          = "MF", ## Molecular Function (MF), Biological Process (BP), and Cellular Component (CC)
              nPerm        = 1000,
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = TRUE,
              by = "fgsea",
              pAdjustMethod = "none") 

## gave 0 enriched genes
```


```{r}
ego2 <- gseGO(geneList     = significant_genes_for_gse,
              OrgDb        = org.Hs.eg.db,
              ont          = "CC", ## Molecular Function (MF), Biological Process (BP), and Cellular Component (CC)
              nPerm        = 1000,
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = TRUE,
              by = "fgsea",
              pAdjustMethod = "none") 
```

```{r}
ego2
```


```{r}
ego3 <- gseGO(geneList     = significant_genes_for_gse,
              OrgDb        = org.Hs.eg.db,
              ont          = "BP", ## Molecular Function (MF), Biological Process (BP), and Cellular Component (CC)
              nPerm        = 1000,
              minGSSize    = 10,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = TRUE,
              by = "fgsea",
              pAdjustMethod = "none") # “holm”, “hochberg”, “hommel”, “bonferroni”, “BH”, “BY”, “fdr”, “none”
```

```{r}
ego3$Description
ego2$Description

ego_all$Description

setdiff(ego2$Description, ego_all$Description)
setdiff(ego3$Description, ego_all$Description) # "cellular response to stress" disappears from list
```

```{r}
goplot(ego3)
```

```{r}
dotplot(ego3, showCategory=10, split=".sign") + facet_grid(.~.sign) + labs(title = 'Gene Functions')
```

```{r}
emapplot(pairwise_termsim(ego3), showCategory = 10)
```



```{r}
library(egg)
d_all <- dotplot(ego_all, showCategory=10, split=".sign") + facet_grid(.~.sign) +  theme(axis.text.y = element_text(hjust = 1, size = 7)) 
d2 <- dotplot(ego2, showCategory=10, split=".sign") + facet_grid(.~.sign)+  theme(axis.text.y = element_text(hjust = 1, size = 7)) 
d3 <- dotplot(ego3, showCategory=10, split=".sign") + facet_grid(.~.sign)+  theme(axis.text.y = element_text(hjust = 1, size = 7)) 

ggarrange(d_all, d2, d3, 
          labels = c("ALL", "CC", "BP"),
          ncol = 1, nrow = 3)
```

```{r}
ridgeplot(ego3) + labs(x = "enrichment distribution") +   theme(axis.text.y = element_text(hjust = 1, size = 7)) 
```


```{r}
gseaplot(ego3, by = "all", title = ego3$Description[1], geneSetID = 1)
```

```{r}
gseaplot(ego3, by = "all", title = ego3$Description[2], geneSetID = 2)
```

```{r}
count_data <- read.table("data/GSE53697_RNAseq_AD.txt", header = TRUE, sep = "\t", row.names = 1) %>%
  dplyr::select(matches("_raw$"))
count_data
```

```{r}
subset_count_data <- count_data[rownames(count_data) %in% as.vector(significant_genes$GeneID),]
subset_count_data
```
```{r}
library("readxl")
metadata <- read_excel('data/ad_metadata.xlsx')
```

```{r}
sampleDist <- cor(subset_count_data, method = "spearman") 
sampleDist

sample_conditions <- data.frame(
  sample = colnames(subset_count_data),
  condition = ifelse(grepl("^C", colnames(subset_count_data)), "HC", "AD"),
  batch = c(0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1),  ## Manually adding batch information; batch effect is a bit serious as otherwise no gene will be identified as significant
  plaque = metadata$BM9_plaque
)
sample_conditions

heat_colors <- list(condition = c("HC" = "#01bfc5", "AD" = "salmon"))

pheatmap(sampleDist,
         annotation_col = sample_conditions$condition,
         annotation_color = heat_colors$condition)

sampleColor <- brewer.pal(3, "Accent")[1:2]
names(sampleColor) <- unique(sample_conditions$condition)

pheatmap(mat = sampleDist,
    cluster_rows = FALSE,
    cluster_cols = FALSE,
    annotation_col = data.frame(Plaque = sample_conditions$plaque, row.names = sample_conditions$sample))


pheatmap(sampleDist,
  clustering_distance_rows = as.dist(1 - sampleDist),
  clustering_distance_cols = as.dist(1 - sampleDist),
  annotation_col = sample_conditions[,c("condition", "plaque")],
  annotation_colors = heat_colors,
  #labels_col = sample_conditions$plaque,
  main = "Sample Correlation Heatmap")
```

```{r}
metadata

```

```{r}
all_genes <- as.data.frame(read_csv('data/all_gene_processed.csv'))
rownames(all_genes) <- all_genes$`...1`
all_genes <- all_genes[,2:6]

voom_normalized <- read_tsv('data/voom_normalized.tsv') 
voom_normalized

gene_cluster <- read_delim('data/cluster1.txt', delim='\n', col_names = FALSE)
gene_cluster_data <- voom_normalized[voom_normalized$GeneSymbol %in% as.vector(gene_cluster$X1),]
genes_for_gse <- all_genes[rownames(all_genes) %in% gene_cluster_data$GeneID,]
 
processed_genes_for_gse <- as.vector(genes_for_gse$logFC)  # p value vector
names(processed_genes_for_gse) <- as.vector(rownames(genes_for_gse)) # gene ids
processed_genes_for_gse <- processed_genes_for_gse[order(-processed_genes_for_gse)] # order ranked
processed_genes_for_gse


ego <- gseGO(geneList     = processed_genes_for_gse,
              OrgDb        = org.Hs.eg.db,
              ont          = "BP", ## Molecular Function (MF), Biological Process (BP), and Cellular Component (CC)
              nPerm        = 1000,
              minGSSize    = 3,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = TRUE,
              by = "fgsea",
              pAdjustMethod = "none")

ego

goplot(ego)
```

```{r}
all_genes <- as.data.frame(read_csv('data/all_gene_processed.csv'))
rownames(all_genes) <- all_genes$`...1`
all_genes <- all_genes[,2:6]

voom_normalized <- read_tsv('data/voom_normalized.tsv') 
voom_normalized

gene_cluster <- read_delim('data/cluster2.txt', delim='\n', col_names = FALSE)
gene_cluster_data <- voom_normalized[voom_normalized$GeneSymbol %in% as.vector(gene_cluster$X1),]
genes_for_gse <- all_genes[rownames(all_genes) %in% gene_cluster_data$GeneID,]
 
processed_genes_for_gse <- as.vector(genes_for_gse$logFC)  # p value vector
names(processed_genes_for_gse) <- as.vector(rownames(genes_for_gse)) # gene ids
processed_genes_for_gse <- processed_genes_for_gse[order(-processed_genes_for_gse)] # order ranked
processed_genes_for_gse


ego <- gseGO(geneList     = processed_genes_for_gse,
              OrgDb        = org.Hs.eg.db,
              ont          = "BP", ## Molecular Function (MF), Biological Process (BP), and Cellular Component (CC)
              nPerm        = 1000,
              minGSSize    = 3,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = TRUE,
              by = "fgsea",
              pAdjustMethod = "none")

ego

goplot(ego)
```


```{r}
all_genes <- as.data.frame(read_csv('data/all_gene_processed.csv'))
rownames(all_genes) <- all_genes$`...1`
all_genes <- all_genes[,2:6]

voom_normalized <- read_tsv('data/voom_normalized.tsv') 
voom_normalized

gene_cluster <- read_delim('data/cluster5.txt', delim='\n', col_names = FALSE)
gene_cluster_data <- voom_normalized[voom_normalized$GeneSymbol %in% as.vector(gene_cluster$X1),]
genes_for_gse <- all_genes[rownames(all_genes) %in% gene_cluster_data$GeneID,]
 
processed_genes_for_gse <- as.vector(genes_for_gse$logFC)  # p value vector
names(processed_genes_for_gse) <- as.vector(rownames(genes_for_gse)) # gene ids
processed_genes_for_gse <- processed_genes_for_gse[order(-processed_genes_for_gse)] # order ranked
processed_genes_for_gse


ego <- gseGO(geneList     = processed_genes_for_gse,
              OrgDb        = org.Hs.eg.db,
              ont          = "BP", ## Molecular Function (MF), Biological Process (BP), and Cellular Component (CC)
              nPerm        = 1000,
              minGSSize    = 3,
              maxGSSize    = 500,
              pvalueCutoff = 0.05,
              verbose      = TRUE,
              by = "fgsea",
              pAdjustMethod = "none")

ego

goplot(ego)
```

